<?php

return [
    'color' => ['required', new \Azuriom\Rules\Color()],
    'banner_enabled' => 'nullable|boolean',
    'banner_color' => 'nullable|string',
    'banner_interval' => 'nullable|integer|min:1|max:60',
    'banner_texts' => 'nullable|array',
    'footer_description' => 'required|string',
    'footer_order' => 'nullable|array',
    'footer_links' => 'nullable|array',
    'legal_links' => 'nullable|array',
    'unique_players' => 'required|integer|min:0',
    'record_players' => 'required|integer|min:0',
    'cta_title' => 'required|string',
    'cta_description' => 'required|string',
    'cta_button_type' => 'required|string|in:server,custom',
    'cta_button_text' => 'nullable|string',
    'cta_button_link' => 'nullable|string|url',
    'about_image' => 'nullable|string',
    'about_title' => 'required|string',
    'about_description' => 'required|string',
    'stats_icon_1' => 'required|string',
    'stats_icon_2' => 'required|string',
    'stats_icon_3' => 'required|string',
    'unique_players_label' => 'required|string',
    'record_players_label' => 'required|string',
    'online_players_label' => 'required|string',
];

